version: '3.4'

services:

    sqldb:
        environment:
            - SA_PASSWORD=Hfsohf@j489d
            - ACCEPT_EULA=Y
        ports:
            - "5433:1433"
        volumes:
            - sql-data:/var/opt/mssql        


    complevo.assesment.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
            - "80"
            - "443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
    sql-data:
        external: false
    